name: Deploy via SSH

on:
  workflow_call:
    secrets:
      host: 
        required: true
      username: 
        required: true
      Key: 
        required: true
      passphrase: 
        required: true
      src: 
        required: true
      target: 
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your workflow can access it
      - uses: actions/checkout@v2

      - name: Create Nodejs server
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install packages
        run: npm install

      - name: Build project        
        run: npm run build --if-present

      - name: Creating .htaccess file
        uses: 1arp/create-a-file-action@0.2
        with:
          path: './dist/'
          file: '.htaccess'
          content: |
            <IfModule mod_negotiation.c>
              Options -MultiViews
            </IfModule>
            <IfModule mod_rewrite.c>
              RewriteEngine On
              RewriteBase /
              RewriteRule ^index\.html$ - [L]
              RewriteCond %{REQUEST_FILENAME} !-f
              RewriteCond %{REQUEST_FILENAME} !-d
              RewriteRule . /index.html [L]
            </IfModule>
            

      # Copying files and artifacts via SSH
      - name: Copying files to server
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          privateKey: ${{ secrets.key }}
          passphrase: ${{ secrets.paraphrase }}
          local: ${{ secrets.src }}
          remote: ${{ secrets.target }}
