name: Deploy via SSH

on:
  workflow_call:
    inputs:
      host: 
        required: true
        type: string
      username: 
        required: true
        type: string
      Key: 
        required: true
        type: string
      passphrase: 
        required: true
        type: string
      src: 
        required: true
        type: string
      target: 
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your workflow can access it
      - uses: actions/checkout@v2

      - name: Create Nodejs server
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install packages
        run: npm install

      - name: Build project        
        run: npm run build --if-present

      # Copying files and artifacts via SSH
      - name: Copying files to server
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ inputs.host }}
          username: ${{ inputs.username }}
          privateKey: ${{ inputs.key }}
          passphrase: ${{ inputs.paraphrase }}
          local: ${{ inputs.src }}
          remote: "${{ inputs.target }}"